"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useKeyPress = exports.useAsyncState = exports.usePrevious = exports.useTitle = exports.useEffectOnce = exports.useUpdateEffect = exports.useUnMount = exports.useMount = exports.useThrottle = exports.useDebounce = exports.useSpinEdit = void 0;
var tslib_1 = require("tslib");
var useSpinEdit_1 = tslib_1.__importDefault(require("./useSpinEdit"));
exports.useSpinEdit = useSpinEdit_1.default;
var useDebounce_1 = tslib_1.__importDefault(require("./useDebounce"));
exports.useDebounce = useDebounce_1.default;
var useThrottle_1 = tslib_1.__importDefault(require("./useThrottle"));
exports.useThrottle = useThrottle_1.default;
var useMount_1 = tslib_1.__importDefault(require("./useMount"));
exports.useMount = useMount_1.default;
var useUnMount_1 = tslib_1.__importDefault(require("./useUnMount"));
exports.useUnMount = useUnMount_1.default;
var useUpdateEffect_1 = tslib_1.__importDefault(require("./useUpdateEffect"));
exports.useUpdateEffect = useUpdateEffect_1.default;
var useEffectOnce_1 = tslib_1.__importDefault(require("./useEffectOnce"));
exports.useEffectOnce = useEffectOnce_1.default;
var useTitle_1 = tslib_1.__importDefault(require("./useTitle"));
exports.useTitle = useTitle_1.default;
var usePrevious_1 = tslib_1.__importDefault(require("./usePrevious"));
exports.usePrevious = usePrevious_1.default;
var useAsyncState_1 = tslib_1.__importDefault(require("./useAsyncState"));
exports.useAsyncState = useAsyncState_1.default;
var useKeyPress_1 = tslib_1.__importDefault(require("./useKeyPress"));
exports.useKeyPress = useKeyPress_1.default;
